// content/transactions.ts
// All transaction data — extracted from source UI and typed.
// To integrate a CMS: replace this export with an async fetch returning Transaction[].

import type { Transaction } from '@/types/transaction';

export const transactions: Transaction[] = [
  {
    id: 'logistics-portfolio-uae',
    name: 'Logistics Portfolio',
    description: '7-asset Grade-A logistics portfolio, UAE Northern Emirates',
    type: 'Logistics',
    market: 'Dubai / Sharjah',
    strategy: 'Core-Plus Acquisition',
    role: 'Buy-Side Advisory',
    year: 2024,
    featured: true,
  },
  {
    id: 'hospitality-campus-ksa',
    name: 'Hospitality Campus',
    description: 'Branded hotel and serviced residences, NEOM Red Sea',
    type: 'Hospitality',
    market: 'KSA',
    strategy: 'Development Advisory',
    role: 'Capital Placement',
    year: 2023,
    featured: true,
  },
  {
    id: 'mixed-use-abu-dhabi',
    name: 'Mixed-Use Development',
    description: '1.2M sqft master-planned community, Abu Dhabi',
    type: 'Mixed-Use',
    market: 'Abu Dhabi',
    strategy: 'Development Structuring',
    role: 'Advisory Mandate',
    year: 2023,
    featured: true,
  },
  {
    id: 'office-tower-difc',
    name: 'Office Tower Disposition',
    description: 'Grade-A strata office, DIFC — full building',
    type: 'Office',
    market: 'Dubai',
    strategy: 'Sell-Side',
    role: 'Sell-Side Advisory',
    year: 2022,
    featured: true,
  },
  {
    id: 'multifamily-dso',
    name: 'Multifamily Portfolio',
    description: '420-unit purpose-built rental, Dubai Silicon Oasis',
    type: 'Residential',
    market: 'Dubai',
    strategy: 'Value-Add',
    role: 'Acquisition & Structuring',
    year: 2022,
    featured: true,
  },
  {
    id: 'industrial-land-ksa',
    name: 'Industrial Land Assembly',
    description: 'Industrial land bank, King Abdullah Economic City',
    type: 'Industrial',
    market: 'KSA',
    strategy: 'Land Strategy',
    role: 'Market Entry Advisory',
    year: 2021,
    featured: true,
  },
  {
    id: 'residential-portfolio-riyadh',
    name: 'Riyadh Residential Portfolio',
    description: '12 residential assets across prime Riyadh districts',
    type: 'Residential',
    market: 'Riyadh',
    strategy: 'Portfolio Review & Disposition',
    role: 'Portfolio Advisory',
    year: 2021,
    featured: false,
  },
  {
    id: 'logistics-jeddah',
    name: 'Jeddah Logistics Hub',
    description: 'Last-mile logistics facility, Jeddah Islamic Port zone',
    type: 'Logistics',
    market: 'KSA',
    strategy: 'Core Acquisition',
    role: 'Buy-Side Advisory',
    year: 2020,
    featured: false,
  },
  {
    id: 'hospitality-doha',
    name: 'Doha Hospitality Asset',
    description: 'International branded hotel, West Bay, Doha',
    type: 'Hospitality',
    market: 'Qatar',
    strategy: 'Value-Add Repositioning',
    role: 'Advisory Mandate',
    year: 2020,
    featured: false,
  },
  {
    id: 'mixed-use-kuwait',
    name: 'Kuwait Mixed-Use Complex',
    description: 'Retail and office mixed-use, Kuwait City Central Business District',
    type: 'Mixed-Use',
    market: 'Kuwait',
    strategy: 'Core',
    role: 'Investment Committee Support',
    year: 2019,
    featured: false,
  },
];
